version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    assignees:
      - "ii1818nn"

  - package-ecosystem: "pip"
    directories:
      - "/ansible"
    schedule:
      interval: "weekly"
    target-branch: "master"
    assignees:
      - "ii1818nn"
