- name: System configuration
  hosts: all

  roles:
    - zsh-configuration
    - brew-packages-installation
    - nvm-installation
    - micro-installation
    - tmux-installation
    - thefuck-installation
    - oh-my-zsh-installation

