- name: Nvm is installed
  ansible.builtin.shell:
    cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
    executable: /bin/zsh
  args:
    creates: "{{ ansible_facts.env.HOME }}/.nvm/nvm.sh"
  environment:
    PROFILE: /dev/null

- name: Dotfiles are copied
  ansible.builtin.copy:
    src: .
    dest: "{{ ansible_facts.env.HOME }}"
    mode: 0644
